### ISSUE TITLE
cannot find function "sdcHier"

### ISSUE THREAD

**Issue by GregorDeCillia** [bernhard-da/sdcHierarchies#11]
The vignette references a function called `sdcHier()`, which cannot be found in the development version or CRAN version of the package.

https://github.com/bernhard-da/sdcHierarchies/blob/e27eac2f93671f017daa489406286c8363f21657/vignettes/usage.Rmd#L210-L215

Did you mean to use `hier_app()` here?

**Comment by bernhard-da** [comment]
@GregorDeCillia thx for spotting it
