### ISSUE TITLE
Wrong @return in docs

### ISSUE THREAD

**Issue by GregorDeCillia** [bernhard-da/sdcHierarchies#13]
The docs of `hier_show()` claim that the function has no return value but only the side effect of printing a tree in the console

https://github.com/bernhard-da/sdcHierarchies/blob/782fc1f05addae59405042ad2c81d4e634a6ed83/R/hier_display.R#L10

In fact, this function returns an object of class `"cli_tree"` which is generated by `cli::tree()`. It is only printed via `cli:::print.cli_tree()` if the user invokes the print method.

```r
data.frame("A", "B") |> cli::tree() |> class()
[1] "cli_tree"        "tree"            "cli_ansi_string" "ansi_string"     "character"
```

I think the most proper solution would be to call `print()` inside the function body of `hier_display()` and return `invisible(NULL)`. That way, everything is consistent with `methods::show()`.

**Comment by bernhard-da** [comment]
@GregorDeCillia  you're right, thx. fixed.
