### ISSUE TITLE
CI recommendations

### ISSUE THREAD

**Issue by GregorDeCillia** [bernhard-da/sdcHierarchies#5]
Hello. Here are some recommendations on how to improve the CI in this package.

- [ ] Setup Appveyor (`devtools::use_appveyor()`) to also check your package on windows.
- [x] Move the Updates part of the README to a file called `NEWS.md`. This works well with `pkgdown`. See [here](https://statistikat.github.io/surveysd/news).
- [x] Allow travis to cache your installations of `lintr` and `pkgdown` by using `r_packages` or `r_github_packages`. See [example](https://github.com/GregorDeCillia/kasper/blob/master/.travis.yml) and [documentation](https://docs.travis-ci.com/user/languages/r/#additional-dependency-fields). I also think it makes sense to move the dependency of `covr` from `DESCRIPTION` to `travis.yml`.

**Comment by bernhard-da** [comment]
@GregorDeCillia thx. quick question. when i specify multiple r-versions in `.travis.yml`, can i specify a single version for which the pkgdown-deployment is done?

**Comment by GregorDeCillia** [comment]
Yes, but I think you need to use a matrix-build in order to do that. See [here](https://github.com/GregorDeCillia/kasper/blob/master/.travis.yml) where I do all the lint-testing, codecov and deployment only for the release version.

**Comment by bernhard-da** [comment]
@GregorDeCillia thx. appveyor perhaps later, i don't care too much about windows, anyway :)

**Comment by GregorDeCillia** [comment]
I understand :). You might want to remove this line since it is now redundant https://github.com/bernhard-da/sdcHierarchies/blob/b5d0c17b7cd79ae7134af97719cc2a65bb4d1255/.travis.yml#L20

**Comment by bernhard-da** [comment]
@GregorDeCillia thx
